### PR TITLE
allow the sandbox to talk to the xdg-run/pipewire-0 socket

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by benzea** [comment]
I am confused. Do we actually need this change?

**Comment by benzea** [comment]
Explanation: gnome-network-displays does use pipewire for recording, but in that case, the FD is passed via DBus.

Now, it also uses pulseaudio, so maybe I am confused and we need access for that on e.g. Fedora where pipewire is used instead of pulseaudio (though, I thought we still connect to the pulseaudio socket in that case).

**Comment by Lctrs** [comment]
I really don't know.

I just noticed that gnd stopped working with my TV few weeks ago out of the blue, and since other flatpak which interacts with pipewire has this, I wanted to test if it would fixes it.

**Comment by benzea** [comment]
Oh, that was probably a gstreamer update, breaking the mpegtxmux interaction. I have no idea what is going on and am hoping for some gstreamer people to fix it.

**Pull request closed without merging**
