### PR TITLE
Don't use git branches

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by Lctrs** [comment]
We use the branch to get auto update from fedc.

**Comment by hfiguiere** [comment]
> We use the branch to get auto update from fedc.

given that fedc isn't setup on this module, I don't see how. but with the current declaration, any commit on the branch will break the flathub build, and that's the intent of the PR.

**Comment by Lctrs** [comment]
When you both specify a branch and a commit, fedc will automatically update the commit to the HEAD of the specified branch, even without an explicit configuration. That's what we want.

**Pull request closed without merging**
